# Generated by Django 5.2.5 on 2025-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'tax'},
        ),
    ]
