# Generated by Django 5.2.5 on 2025-09-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='fooditem',
            new_name='product',
        ),
    ]
