# Generated by Django 5.2.5 on 2025-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_fooditem_orderedproduct_product'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sellers',
            field=models.ManyToManyField(blank=True, to='seller.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
